// Data Resmi Sertifikat & Surat Keputusan (SK) Akreditasi 21 Program Studi Fakultas Vokasi USU
// Sumber: public/akreditasi/

export const AKREDITASI_DATA = [
  {
    id: 'akred-d3-akuntansi',
    prodi: 'D3 Akuntansi',
    jenjang: 'D3',
    lembaga: 'LAMEMBA',
    peringkat: 'Baik Sekali',
    noSk: '1124/DE/A.5/AR.10/III/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Akuntansi (2024-2029).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Akuntansi (2024-2029).pdf',
    fileSize: '1.09 MB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Lembaga Akreditasi Mandiri Ekonomi Manajemen Bisnis dan Akuntansi (LAMEMBA).'
  },
  {
    id: 'akred-d3-kesekretariatan',
    prodi: 'D3 Kesekretariatan',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '1350/SK/BAN-PT/Ak.KP/D3/IV/2023',
    masaBerlaku: '2023 - 2026',
    tanggalKedaluwarsa: '2026',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Kesekretariatan (2023-2026).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Kesekretariatan (2023-2026).pdf',
    fileSize: '728 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).'
  },
  {
    id: 'akred-d3-keuangan',
    prodi: 'D3 Keuangan',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '715/SK/BAN-PT/Ak.Ppj/D3/III/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Keuangan (2024 - 2029).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Keuangan (2024 - 2029).pdf',
    fileSize: '750 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).'
  },
  {
    id: 'akred-d3-anafarma',
    prodi: 'D3 Analis Farmasi dan Makanan',
    jenjang: 'D3',
    lembaga: 'LAM-PTKes',
    peringkat: 'Unggul',
    noSk: '0142/LAM-PTKes/Akr/Dip/III/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi D3 ANAFARMA 2024-2029.pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi D3 ANAFARMA 2024-2029.pdf',
    fileSize: '1.31 MB',
    keterangan: 'Salinan resmi Surat Keputusan Perkumpulan Lembaga Akreditasi Mandiri Pendidikan Tinggi Kesehatan Indonesia (LAM-PTKes).'
  },
  {
    id: 'akred-d3-perpajakan',
    prodi: 'D3 Perpajakan',
    jenjang: 'D3',
    lembaga: 'LAMEMBA',
    peringkat: 'Baik Sekali',
    noSk: '642/DE/A.5/AR.10/VIII/2023',
    masaBerlaku: '2023 - 2028',
    tanggalKedaluwarsa: '2028',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Perpajakan 2023-2028.pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Perpajakan 2023-2028.pdf',
    fileSize: '1.09 MB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Lembaga Akreditasi Mandiri Ekonomi Manajemen Bisnis dan Akuntansi (LAMEMBA).'
  },
  {
    id: 'akred-d3-bahasa-inggris',
    prodi: 'D3 Bahasa Inggris',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '4276/SK/BAN-PT/Ak.Ppj/D3/X/2023',
    masaBerlaku: '2023 - 2028',
    tanggalKedaluwarsa: '2028',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Bahasa Inggris (2023-2028).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Bahasa Inggris (2023-2028).pdf',
    fileSize: '728 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).'
  },
  {
    id: 'akred-d3-bahasa-jepang',
    prodi: 'D3 Bahasa Jepang',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '1817/SK/BAN-PT/Ak.Ppj/D3/V/2023',
    masaBerlaku: '2023 - 2028',
    tanggalKedaluwarsa: '2028',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi Bahasa Jepang (2023-2028).pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi Bahasa Jepang (2023-2028).pdf',
    fileSize: '68 KB',
    keterangan: 'Salinan resmi Surat Keputusan Direktur Dewan Eksekutif BAN-PT.'
  },
  {
    id: 'akred-d3-perpustakaan',
    prodi: 'D3 Perpustakaan',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '3494/SK/BAN-PT/Ak.Ppj/D3/VIII/2023',
    masaBerlaku: '2023 - 2028',
    tanggalKedaluwarsa: '2028',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Perpustakaan (2023-2028).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Perpustakaan (2023-2028).pdf',
    fileSize: '728 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).'
  },
  {
    id: 'akred-d3-perjalanan-wisata',
    prodi: 'D3 Perjalanan Wisata',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '3711/SK/BAN-PT/Ak.KP/D3/IV/2024',
    masaBerlaku: '2024 - 2028',
    tanggalKedaluwarsa: '2028',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Perjalanan Wisata (2024-2028).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Perjalanan Wisata (2024-2028).pdf',
    fileSize: '750 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).'
  },
  {
    id: 'akred-d3-fisika',
    prodi: 'D3 Fisika',
    jenjang: 'D3',
    lembaga: 'LAMSAMA',
    peringkat: 'Baik Sekali',
    noSk: '009/SK/LAMSAMA/Akred/DIII/XII/2022',
    masaBerlaku: '2022 - 2027',
    tanggalKedaluwarsa: '2027',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Fisika (2022-2027).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Fisika (2022-2027).pdf',
    fileSize: '606 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Lembaga Akreditasi Mandiri Sains Alam dan Ilmu Formal (LAMSAMA).'
  },
  {
    id: 'akred-d3-kimia',
    prodi: 'D3 Kimia',
    jenjang: 'D3',
    lembaga: 'BAN-PT',
    peringkat: 'B',
    noSk: '619/SK/BAN-PT/Ak.KP/D3/II/2023',
    masaBerlaku: '2023 - 2027',
    tanggalKedaluwarsa: '2027',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Kimia (2023-2027).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Kimia (2023-2027).pdf',
    fileSize: '728 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).'
  },
  {
    id: 'akred-d3-teknik-informatika',
    prodi: 'D3 Teknik Informatika',
    jenjang: 'D3',
    lembaga: 'LAM INFOKOM',
    peringkat: 'Baik Sekali',
    noSk: '059/SK/LAM-INFOKOM/Ak/D3/XII/2022',
    masaBerlaku: '2022 - 2027',
    tanggalKedaluwarsa: '2027',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Teknik Informatika (2022-2027).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Teknik Informatika (2022-2027).pdf',
    fileSize: '244 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Lembaga Akreditasi Mandiri Informatika dan Komputer (LAM INFOKOM).'
  },
  {
    id: 'akred-d3-metrologi',
    prodi: 'D3 Metrologi dan Instrumentasi',
    jenjang: 'D3',
    lembaga: 'LAMSAMA',
    peringkat: 'Baik Sekali',
    noSk: '038/SK/LAMSAMA/Akred/DIII/VI/2023',
    masaBerlaku: '2023 - 2027',
    tanggalKedaluwarsa: '2027',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi Metrologi dan Instrumentasi (2023-2027).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi Metrologi dan Instrumentasi (2023-2027).pdf',
    fileSize: '130 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Lembaga Akreditasi Mandiri Sains Alam dan Ilmu Formal (LAMSAMA).'
  },
  {
    id: 'akred-d3-statistika',
    prodi: 'D3 Statistika',
    jenjang: 'D3',
    lembaga: 'LAMSAMA',
    peringkat: 'Baik Sekali',
    noSk: '012/SK/LAMSAMA/Akred/DIII/XII/2022',
    masaBerlaku: '2022 - 2027',
    tanggalKedaluwarsa: '2027',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi Statistika (2022-2027).pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi Statistika (2022-2027).pdf',
    fileSize: '658 KB',
    keterangan: 'Salinan resmi Surat Keputusan LAMSAMA Program Studi Diploma Tiga Statistika.'
  },
  {
    id: 'akred-d4-perbankan',
    prodi: 'D4 Perbankan dan Keuangan',
    jenjang: 'D4',
    lembaga: 'LAMEMBA',
    peringkat: 'Baik',
    noSk: '259/DE/A.5/AR.11/II/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi D4 Perbankan Dan Keuangan.pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi D4 Perbankan Dan Keuangan.pdf',
    fileSize: '594 KB',
    keterangan: 'Salinan resmi SK Pemenuhan Syarat Minimum Akreditasi LAMEMBA Program Sarjana Terapan.'
  },
  {
    id: 'akred-d4-perkantoran-digital',
    prodi: 'D4 Administrasi Perkantoran Digital',
    jenjang: 'D4',
    lembaga: 'LAMEMBA',
    peringkat: 'Baik',
    noSk: '257/DE/A.5/AR.11/II/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi D4 Administrasi Perkantoran Digital.pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi D4 Administrasi Perkantoran Digital.pdf',
    fileSize: '593 KB',
    keterangan: 'Salinan resmi SK Pemenuhan Syarat Minimum Akreditasi LAMEMBA Program Sarjana Terapan.'
  },
  {
    id: 'akred-d4-akuntansi-sektor-publik',
    prodi: 'D4 Akuntansi Sektor Publik',
    jenjang: 'D4',
    lembaga: 'LAMEMBA',
    peringkat: 'Baik',
    noSk: '256/DE/A.5/AR.11/II/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi D4 Akuntansi Sektor Publik.pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi D4 Akuntansi Sektor Publik.pdf',
    fileSize: '502 KB',
    keterangan: 'Salinan resmi SK Pemenuhan Syarat Minimum Akreditasi LAMEMBA Program Sarjana Terapan.'
  },
  {
    id: 'akred-d4-statistika',
    prodi: 'D4 Statistika',
    jenjang: 'D4',
    lembaga: 'LAMSAMA',
    peringkat: 'Baik',
    noSk: '096/SK/LAMSAMA/Akred/STr/IV/2026',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi D4 Statistik.pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi D4 Statistik.pdf',
    fileSize: '606 KB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi LAMSAMA Program Sarjana Terapan Statistika.'
  },
  {
    id: 'akred-d4-kimia-terapan',
    prodi: 'D4 Kimia Terapan',
    jenjang: 'D4',
    lembaga: 'LAMSAMA',
    peringkat: 'Baik',
    noSk: '105/SK/LAMSAMA/Akred/STr/V/2026',
    masaBerlaku: '2026 - 2031',
    tanggalKedaluwarsa: '2031',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Akreditasi D4 Kimia Terapan (2026-2031).pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Akreditasi D4 Kimia Terapan (2026-2031).pdf',
    fileSize: '2.18 MB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi LAMSAMA Program Sarjana Terapan Kimia Terapan.'
  },
  {
    id: 'akred-d4-bisnis-pariwisata',
    prodi: 'D4 Manajemen Bisnis Pariwisata',
    jenjang: 'D4',
    lembaga: 'LAMEMBA',
    peringkat: 'Baik',
    noSk: '258/DE/A.5/AR.11/II/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan SK Akreditasi D4 Manajemen Bisnis Pariwisata.pdf',
    fileUrl: '/akreditasi/Salinan SK Akreditasi D4 Manajemen Bisnis Pariwisata.pdf',
    fileSize: '594 KB',
    keterangan: 'Salinan resmi SK Pemenuhan Syarat Minimum Akreditasi LAMEMBA Program Sarjana Terapan.'
  },
  {
    id: 'akred-d4-rekayasa-instrumentasi',
    prodi: 'D4 Teknologi Rekayasa dan Instrumentasi',
    jenjang: 'D4',
    lembaga: 'LAM Teknik',
    peringkat: 'Baik',
    noSk: '0128/SK/LAM Teknik/AS/STr/VIII/2024',
    masaBerlaku: '2024 - 2029',
    tanggalKedaluwarsa: '2029',
    status: 'Aktif',
    fileName: 'Salinan Sertifikat Terakreditasi D4 Teknologi Rekayasa Instrumentasi 2026.pdf',
    fileUrl: '/akreditasi/Salinan Sertifikat Terakreditasi D4 Teknologi Rekayasa Instrumentasi 2026.pdf',
    fileSize: '1.14 MB',
    keterangan: 'Salinan resmi Sertifikat Akreditasi Lembaga Akreditasi Mandiri Program Studi Keteknikan (LAM Teknik).'
  }
];
